#!/usr/bin/env bash
# cleanup-old-install.sh
#
# Detects and removes artifacts left by the old C++ aliases install.sh,
# so you can start fresh with `aliases setup` (Python/uv version).
#
# What it looks for:
#   - ~/.local/bin/aliases      C++ ELF binary installed by old install.sh
#   - ~/.bash_aliases               File generated by old install.sh with ALIASES_DIR + C++ markers
#   - ~/.bash_aliases.bak           Backup left by old install.sh's update logic
#   - ~/.bashrc                     Source line added by old setup (kept — new setup needs it too)
#   - ~/.config/aliases/        Left intact — new Python setup uses the same location
#
# Usage:
#   bash cleanup-old-install.sh          # dry-run: show what would be removed
#   bash cleanup-old-install.sh --apply  # actually remove / rewrite files

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[info]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC}  $*"; }
ok()      { echo -e "${GREEN}[ok]${NC}    $*"; }
removed() { echo -e "${RED}[rm]${NC}    $*"; }

# ── Args ─────────────────────────────────────────────────────────────────────
DRY_RUN=true
for arg in "$@"; do
  [[ "$arg" == "--apply" ]] && DRY_RUN=false
done

if $DRY_RUN; then
  warn "DRY-RUN mode — nothing will be changed. Re-run with --apply to apply."
  echo
fi

do_rm() {
  local path="$1"
  if $DRY_RUN; then
    removed "would remove: $path"
  else
    rm -f "$path"
    removed "removed: $path"
  fi
}

do_rewrite() {
  local path="$1" content="$2"
  if $DRY_RUN; then
    warn "would rewrite: $path"
  else
    printf '%s' "$content" > "$path"
    ok "rewrote: $path"
  fi
}

# ── 1. Old C++ binary at ~/.local/bin/aliases ────────────────────────────
OLD_BIN="$HOME/.local/bin/aliases"
if [[ -f "$OLD_BIN" ]]; then
  filetype=$(file -b "$OLD_BIN" 2>/dev/null || echo "unknown")
  if [[ "$filetype" == ELF* ]]; then
    removed "found old C++ binary: $OLD_BIN  ($filetype)"
    do_rm "$OLD_BIN"
  else
    info "skipping $OLD_BIN — does not look like an ELF binary ($filetype)"
  fi
else
  ok "no old binary at $OLD_BIN"
fi

# ── 2. ~/.bash_aliases backup left by old installer ──────────────────────────
if [[ -f "$HOME/.bash_aliases.bak" ]]; then
  warn "found installer backup: ~/.bash_aliases.bak"
  do_rm "$HOME/.bash_aliases.bak"
else
  ok "no ~/.bash_aliases.bak"
fi

# ── 3. ~/.bash_aliases generated by old install.sh ───────────────────────────
BA="$HOME/.bash_aliases"
if [[ -f "$BA" ]]; then
  is_old=false

  # Marker 1: "C++ ALIASES-CLI INTEGRATION" block header
  grep -q "C++ ALIASES-CLI INTEGRATION" "$BA" 2>/dev/null && is_old=true

  # Marker 2: ALIASES_DIR= pointing to a git clone path (not to ~/.config)
  grep -qE '^ALIASES_DIR="' "$BA" 2>/dev/null && is_old=true

  # Marker 3: alias pointing to $ALIASES_DIR/aliases (bare binary)
  grep -qE "alias (aliases|a|c)='\\\$ALIASES_DIR" "$BA" 2>/dev/null && is_old=true

  if $is_old; then
    warn "~/.bash_aliases looks like it was generated by the old C++ installer:"
    grep -n "ALIASES_DIR\|C++ ALIASES-CLI\|alias aliases\|alias a=\|alias c=" "$BA" 2>/dev/null \
      | head -10 | sed 's/^/        /'
    echo

    if $DRY_RUN; then
      removed "would remove ~/.bash_aliases (old C++ version)"
      info "After --apply, run: aliases setup"
    else
      # Back it up then remove — new `aliases setup` will recreate it
      backup="$HOME/.bash_aliases.old-cpp-$(date +%Y%m%d%H%M%S)"
      cp "$BA" "$backup"
      ok "backed up to: $backup"
      do_rm "$BA"
      info "Run 'aliases setup' to install the new Python-based ~/.bash_aliases"
    fi
  else
    ok "~/.bash_aliases does not match old C++ installer pattern — leaving untouched"
  fi
else
  ok "no ~/.bash_aliases found"
fi

# ── 4. ~/.bashrc — source line for ~/.bash_aliases ───────────────────────────
# The old installer did NOT add this line; users added it manually.
# The new `aliases setup` adds it too, so we leave it alone either way.
BASHRC="$HOME/.bashrc"
if [[ -f "$BASHRC" ]] && grep -q 'source.*\.bash_aliases\|\..*\.bash_aliases' "$BASHRC" 2>/dev/null; then
  ok "~/.bashrc already has a source line for ~/.bash_aliases — keeping it (needed by new setup too)"
fi

# ── 5. Old ALIASES_DIR sourcing lines inside ~/.bashrc ───────────────────────
# Some users had ALIASES_DIR set directly in ~/.bashrc pointing to the git clone.
# That's stale now that the binary comes from uv tools and config from ~/.config.
if [[ -f "$BASHRC" ]]; then
  old_lines=$(grep -nE '^ALIASES_DIR=|source.*\$ALIASES_DIR|export ALIASES_DIR' "$BASHRC" 2>/dev/null || true)
  if [[ -n "$old_lines" ]]; then
    warn "~/.bashrc contains ALIASES_DIR references from old setup:"
    echo "$old_lines" | sed 's/^/        /'
    echo
    if $DRY_RUN; then
      removed "would remove ALIASES_DIR lines from ~/.bashrc"
    else
      backup_rc="$HOME/.bashrc.old-cpp-$(date +%Y%m%d%H%M%S)"
      cp "$BASHRC" "$backup_rc"
      ok "backed up ~/.bashrc to: $backup_rc"
      # Remove lines that set/export/source ALIASES_DIR
      grep -vE '^ALIASES_DIR=|source.*\$ALIASES_DIR|export ALIASES_DIR' "$BASHRC" > "${BASHRC}.tmp"
      mv "${BASHRC}.tmp" "$BASHRC"
      removed "removed ALIASES_DIR lines from ~/.bashrc"
    fi
  else
    ok "no stale ALIASES_DIR lines in ~/.bashrc"
  fi
fi

# ── 6. ~/.config/aliases — NOT touched ───────────────────────────────────
if [[ -d "$HOME/.config/aliases" ]]; then
  info "~/.config/aliases/ exists — left intact (reused by Python version)"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo
if $DRY_RUN; then
  echo -e "${YELLOW}Re-run with --apply to actually apply the changes above.${NC}"
  echo
  echo "  bash cleanup-old-install.sh --apply"
else
  echo -e "${GREEN}Cleanup complete.${NC}"
  echo
  echo "Next: install the Python version and run setup:"
  echo "  uv tool install git+https://github.com/bbauer0706/aliases"
  echo "  aliases setup"
fi
