"""Tests for ``aliases setup --update`` – the refresh path used by ``aliases update``."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest
from click.testing import CliRunner

from aliases.main import cli


@pytest.fixture
def home(tmp_path: Path):
    """Redirect Path.home() so setup writes into tmp_path, never the real $HOME."""
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    with patch.object(Path, "home", return_value=fake_home):
        yield fake_home


class TestSetupUpdate:
    def test_installs_shell_files(self, runner: CliRunner, home: Path, isolated_config):
        result = runner.invoke(cli, ["setup", "--update"])
        assert result.exit_code == 0
        assert (isolated_config.config_dir / "shell" / "prompt.sh").exists()

    def test_regenerates_stale_bash_aliases(self, runner: CliRunner, home: Path):
        bash_aliases = home / ".bash_aliases"
        bash_aliases.write_text("# stale content from an older version\n", encoding="utf-8")

        result = runner.invoke(cli, ["setup", "--update"])

        assert result.exit_code == 0
        content = bash_aliases.read_text(encoding="utf-8")
        assert "stale content" not in content
        assert "Generated by: aliases setup" in content
        assert (home / ".bash_aliases.bak").exists()  # old version preserved

    def test_no_rewrite_when_already_current(self, runner: CliRunner, home: Path):
        runner.invoke(cli, ["setup", "--update"])  # first run creates nothing yet
        bash_aliases = home / ".bash_aliases"
        from aliases.commands.setup_cmd import _generate_bash_aliases
        from aliases.config import Config

        bash_aliases.write_text(
            _generate_bash_aliases(Config.instance().config_dir), encoding="utf-8"
        )

        result = runner.invoke(cli, ["setup", "--update"])

        assert result.exit_code == 0
        assert not (home / ".bash_aliases.bak").exists()  # no pointless backup

    def test_leaves_bashrc_alone(self, runner: CliRunner, home: Path):
        bashrc = home / ".bashrc"
        bashrc.write_text("# untouched\n", encoding="utf-8")

        result = runner.invoke(cli, ["setup", "--update"])

        assert result.exit_code == 0
        assert bashrc.read_text(encoding="utf-8") == "# untouched\n"


class TestBinDirOnPath:
    """Stock ~/.bashrc sources ~/.bash_aliases before adding ~/.local/bin to PATH.

    Without a PATH fix-up the `aliases` calls inside the integration files fail
    silently, so eza ignores eza.icons and the prompt stays on its fallback
    until the first cd.
    """

    def test_prepends_bin_dir_before_sourcing(self, home: Path):
        from aliases.commands.setup_cmd import _generate_bash_aliases

        content = _generate_bash_aliases(home / ".config" / "aliases")

        path_block = content.index('PATH="$_ali_bin:')
        assert path_block < content.index("prompt.sh")
        assert path_block < content.index(".ali.sh")

    def test_always_includes_local_bin(self, home: Path):
        from aliases.commands.setup_cmd import _aliases_bin_dirs

        # A dev-checkout venv must never be the only entry baked into the file.
        assert str(home / ".local" / "bin") in _aliases_bin_dirs()
