name: Release (Tag-triggered)

# This workflow is triggered when a tag is pushed manually
# For automatic releases, see ci-cd.yml

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++
      
      - name: Build binary
        run: ./build.sh
      
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Rename binary
        run: |
          cp build/aliases-cli build/aliases-cli-${{ steps.get_version.outputs.VERSION }}-linux-x86_64
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/aliases-cli-${{ steps.get_version.outputs.VERSION }}-linux-x86_64
            CHANGELOG.md
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
